server:
    port: 8181
    servlet:
        context-path: /api

spring:
    profiles:
        active: dev
    application:
        name: ordinainchat
    data:
        mongodb:
            authentication-database: admin
            database: ${SPRING_DATA_MONGODB_DATABASE:ordinainchat-db}
            host: ${SPRING_DATA_MONGODB_HOST:localhost}
            password: ${SPRING_DATA_MONGODB_PASSWORD:secr3t}
            port: ${SPRING_DATA_MONGODB_PORT:6481}
            username: ${SPRING_DATA_MONGODB_USERNAME:admin}
            auto-index-creation: true        

springdoc:
    api-docs:
        path: /api-docs
    swagger-ui:
        path: /swagger-ui.html  
        operationsSorter: method        

openapi:
    service:
        title: "TAF Development API"
        version: 1.0.0
        url: ${OPENAPI_URL:http://localhost:8080/v3/api-docs}          